polls/urls.py
from django.conf.urls import url
from . import views

app_name = 'polls'
urlpatterns = [
    url(r'^$', views.IndexView.as_view(), name='index'),
    url(r'^(?P<pk>[0-9]+)/$', views.DetailView.as_view(), name='detail'),
    url(r'^(?P<pk>[0-9]+)/results/$', views.ResultsView.as_view(), name='results'),
    url(r'^(?P<question_id>[0-9]+)/vote/$', views.vote, name='vote'),
]

trash/urls.py
from django.conf.urls import url
from . import views

app_name = 'trash'
urlpatterns = [
    url(r'^$', views.IndexView.as_view(), name='index'),
    url(r'^(?P<pk>[0-9]+)/detail_trash$', views.DetailTrashView.as_view(), name='detail_trash'),
    url(r'^(?P<trashsetting_id>[0-9]+)/file_list$', views.file_list, name='file_list'),
    url(r'^(?P<trashsetting_id>[0-9]+)/delete_files', views.delete_files, name='delete_files'),
]

webmyrm/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^polls/', include('polls.urls')),
    url(r'^trash/', include('trash.urls')),
    url(r'^admin/', admin.site.urls),
]

polls/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
import datetime
from django.utils import timezone
from django.db import models


class Question(models.Model):
    question_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField('date published')

    def __str__(self):
        return self.question_text

    def was_published_recently(self):
        return self.pub_date >= timezone.now() - datetime.timedelta(days=1)


class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)

    def __str__(self):
        return self.choice_text

trash/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
from django.utils import timezone
from django.db import models
import os


class TrashSetting(models.Model):
    path_to_log = models.CharField(default=os.path.join(os.getcwd(), '.log_myrm_itislogfilemyrm_'), max_length=200)
    path_to_trash = models.CharField(default=os.path.join(os.getcwd(), '.mytrash'), max_length=200)
    call_auto_cleaning_if_memory_error = models.BooleanField(default=False)
    dry = models.BooleanField(default=False)
    last_cleaning_date = models.DateTimeField(default=timezone.now())
    level_log = models.IntegerField(default=10)
    max_size_for_start_cleaning = models.IntegerField(default=2000000000)
    min_day_for_start_cleaning = models.IntegerField(default=14)
    policy = models.IntegerField(default=0)
    resolve_conflict = models.BooleanField(default=True)
    show_bar_status = models.BooleanField(default=False)
    silent = models.BooleanField(default=False)
    with_confirmation = models.BooleanField(default=False)

    def __str__(self):
        return self.path_to_trash

polls/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
from django.shortcuts import get_object_or_404, render
from .models import Choice, Question
from django.http import HttpResponseRedirect, HttpResponse
from django.core.urlresolvers import reverse
from django.views import generic


class IndexView(generic.ListView):
    template_name = 'polls/index.html'
    context_object_name = 'latest_question_list'

    def get_queryset(self):
        """Return the last five published questions."""
        return Question.objects.order_by('-pub_date')[:5]


class DetailView(generic.DetailView):
    model = Question
    template_name = 'polls/detail.html'


class ResultsView(generic.DetailView):
    model = Question
    template_name = 'polls/results.html'


def vote(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    try:
        selected_choice = question.choice_set.get(pk=request.POST['choice'])
    except (KeyError, Choice.DoesNotExist):
        # Redisplay the question voting form.
        return render(request, 'polls/detail.html', {
            'question': question,
            'error_message': "You didn't select a choice.",
        })
    else:
        selected_choice.votes += 1
        selected_choice.save()
        # Always return an HttpResponseRedirect after successfully dealing
        # with POST data. This prevents data from being posted twice if a
        # user hits the Back button.
        return HttpResponseRedirect(reverse('polls:results', args=(question.id,)))

trash/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
from __future__ import unicode_literals
from django.shortcuts import get_object_or_404, render
from django.http import HttpResponseRedirect, HttpResponse
from django.core.urlresolvers import reverse
from django.views import generic
from .models import TrashSetting
from django.shortcuts import render
import os
from myrm.main_logic import deleting_files


class IndexView(generic.ListView):
    template_name = 'trash/index.html'
    context_object_name = 'trash_list'

    def get_queryset(self):
        """Return the trashes."""
        return TrashSetting.objects.order_by('-path_to_trash')


class DetailTrashView(generic.DetailView):
    model = TrashSetting
    context_object_name = 'trash'
    template_name = 'trash/detail_trash.html'


def file_list(request, trashsetting_id):
    dir_list = []
    file_list = []
    folder = os.getcwd()

    for dirpath, dirs, files in os.walk(folder):
        for file in files:
            path = os.path.join(dirpath, file)
            file_list.append(path)

        for dir in dirs:
            path = os.path.join(dirpath, dir)
            dir_list.append(path)
        break

    return render(request, 'trash/file_list.html', {
        'file_list': file_list,
        'dir_list': dir_list,
        'folder': folder,
    })

def delete_files(request, trashsetting_id):

polls/templates/polls/detail.html
<h1>{{ question.question_text }}</h1>

{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}

<form action="{% url 'polls:vote' question.id %}" method="post">
{% csrf_token %}
{% for choice in question.choice_set.all %}
    <input type="radio" name="choice" id="choice{{ forloop.counter }}" value="{{ choice.id }}" />
    <label for="choice{{ forloop.counter }}">{{ choice.choice_text }}</label><br />
{% endfor %}
<input type="submit" value="Vote" />
</form>

polls/templates/polls/index.html
{% load staticfiles %}

<link rel="stylesheet" type="text/css" href="{% static 'polls/style.css' %}" />

{% if latest_question_list %}
    <ul>
    {% for question in latest_question_list %}
        <li><a href="{% url 'polls:detail' question.id %}">{{ question.question_text }}</a></li>
    {% endfor %}
    </ul>
{% else %}
    <p>No polls are available.</p>
{% endif %}

polls/templates/polls/results.html
<h1>{{ question.question_text }}</h1>

<ul>
{% for choice in question.choice_set.all %}
    <li>{{ choice.choice_text }} -- {{ choice.votes }} vote{{ choice.votes|pluralize }}</li>
{% endfor %}
</ul>

<a href="{% url 'polls:detail' question.id %}">Vote again?</a>

trash/templates/trash/delete_files.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<form action="{% url 'trash:deleting_files' trash.id %}" method="post">
{% csrf_token %}
    <input type="text"  />
    <br/>
{% endfor %}
<input type="submit" value="delete" />
</form>
</body>
</html>

trash/templates/trash/detail_trash.html
<h3>You are selected trash with path: {{ trash.path_to_trash }}</h3>
choose action:
<ul>
    <li><a href="{% url 'trash:file_list' trash.id %}">view file list</a></li>
    <li><a href="{% url 'trash:delete_files' trash.id %}">delete files</a></li>
</ul>

trash/templates/trash/file_list.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>File list</title>
</head>
<body>
    <h3>you are in the "{{ folder }}" folder</h3>
{% if dir_list and file_list %}
    dirs:
    <ul>
    {% for dir in dir_list %}
        {#<li><a href="{% url 'trash:view_directory' dir%}">{{ dir }}</a></li>#}
        <li>{{ dir }}</li>
    {% endfor %}
    </ul>
    files:
    <ul>
    {% for file in file_list %}
        <li>{{ file }}</li>
    {% endfor %}
    </ul>
{% else %}
    <p>No dirs & files are available.</p>
{% endif %}

</body>
</html>

trash/templates/trash/index.html
{% if trash_list %}
    <h2>Choose trash</h2>
    <ul>
    {% for trash in trash_list %}
        <li><a href="{% url 'trash:detail_trash' trash.id %}">{{ trash.path_to_trash }}</a></li>
    {% endfor %}
    </ul>
{% else %}
    <p>No trash are available.</p>
{% endif %}